apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
  - port: 3000
    name: node-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: tunlyinaung/node-app:v1.0.2 # {"$imagepolicy": "flux-system:node-app"}
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: '100Mi'
            cpu: '25m'
          limits:
            memory: '100Mi'
            cpu: '25m'
